In [2]:
import tensorflow as tf

#TensorFlow 2 quickstart for beginners
This short introduction uses Keras to:

Build a neural network that classifies images.
Train this neural network.
And, finally, evaluate the accuracy of the model.
load the mnist dataset 

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0



11493376/11490434 [==============================] - 0s 0us/step


#Build the tf.keras.Sequential model by stacking layers. Choose an optimizer and loss function for training:
For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.10271885,  0.49922198,  0.5934531 ,  0.94570637, -0.33423427,
         0.3495865 , -0.16191898,  0.5330763 , -0.03664055,  0.47997186]],
      dtype=float32)

#The tf.nn.softmax function converts these logits to "probabilities" for each class:

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.0769058 , 0.11432948, 0.1256268 , 0.17867506, 0.04968128,
        0.09844017, 0.05902396, 0.11826628, 0.06690153, 0.11214967]],
      dtype=float32)

#The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.3183064

#The Model.fit method adjusts the model parameters to minimize the loss:

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model.fit(x_train, y_train, epochs=4)

Epoch 1/4
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2934 - accuracy: 0.9151
Epoch 2/4
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1414 - accuracy: 0.9580
Epoch 3/4
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1050 - accuracy: 0.9684
Epoch 4/4
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0869 - accuracy: 0.9733


In [8]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0880 - accuracy: 0.9731


[0.08796904981136322, 0.9731000065803528]

In [9]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.71262187e-07, 1.65380154e-08, 1.33405013e-06, 1.18153682e-03,
        1.37187154e-11, 1.95245684e-06, 4.21254069e-13, 9.98810768e-01,
        1.13037302e-07, 4.10042639e-06],
       [2.78604251e-08, 3.81801068e-03, 9.95940208e-01, 2.34902036e-04,
        8.19460500e-15, 6.45906357e-06, 3.01788333e-07, 1.43197025e-11,
        7.07017378e-08, 1.24007727e-12],
       [7.91954517e-06, 9.89461482e-01, 2.71140219e-04, 8.88371360e-05,
        3.36665747e-04, 2.96407728e-04, 6.08269511e-05, 9.02025681e-03,
        4.17029572e-04, 3.93997398e-05],
       [9.98819292e-01, 6.85820964e-08, 2.77811458e-04, 1.01384126e-06,
        2.90302014e-05, 1.08173072e-05, 3.17916973e-04, 4.89875558e-04,
        6.23711571e-08, 5.40654983e-05],
       [4.17328738e-06, 1.90370235e-06, 1.73084554e-05, 4.39618447e-07,
        9.86702502e-01, 4.41761443e-07, 5.01595605e-06, 1.72284446e-04,
        1.90309970e-06, 1.30941113e-02]], dtype=float32)>